apiVersion: v1
kind: Pod
metadata:
        name: petclinic 
spec:
       containers:
               - name: mysql 
                 image: mysql
                 env:
                 - name: MYSQL_ROOT_PASSWORD
                   value: petclinic
               - name: petclinic
                 image: anthonydahanne/spring-petclinic 
