apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 53
  selector:
    tier: web 
  template:
    metadata:
      name: nginx
      labels:
       tier: web 
    spec:
      containers:
      - name: nginx
        image: nginx
