apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql 
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: petclinic
        ports:
        - containerPort: 3306
